spring.application.name=Bookstore-Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore-db
spring.datasource.username=postgres
spring.datasource.password=Postgres@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#for jwt
#jwt.secret=7b4f9d82c1e8a6f3d0b74ea91f6c28ab53de71984ac0f5b2e1679d3cf84ab65190e7f4c21b8d6a53ef0972bc41d8a6f59ce13ab74d2086e5f1c9b8d4a7e26f30
#jwt.expiration=86400000

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#rabbit
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true